apiVersion: v1
kind: Service
metadata:
  # name of service
  name: diamond
spec:
  type: LoadBalancer # LoadBalancer or ClusterIP
  selector:
    # which pods qualify for forwarding the requests
    app: diamond
  ports:
    - port: 80 # port on the service
      targetPort: 9696 # port on the pod
